spring.application.name=growecom

spring.datasource.url=jdbc:postgresql://localhost:5432/growecom
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.security.user.password=springstudent
spring.security.user.name=springstudent